//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message/super.online.proto
namespace SuperOnlineProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_LoginOnline")]
  public partial class Msg_C2S_LoginOnline : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_LoginOnline() {}
    
    private int _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private int _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private byte[] _session;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] session
    {
      get { return _session; }
      set { _session = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private int _dev_type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dev_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dev_type
    {
      get { return _dev_type; }
      set { _dev_type = value; }
    }
    private int _cli_version;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"cli_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cli_version
    {
      get { return _cli_version; }
      set { _cli_version = value; }
    }
    private string _apn_token = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"apn_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apn_token
    {
      get { return _apn_token; }
      set { _apn_token = value; }
    }
    private string _android_mac = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"android_mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_mac
    {
      get { return _android_mac; }
      set { _android_mac = value; }
    }
    private string _android_adid = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"android_adid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_adid
    {
      get { return _android_adid; }
      set { _android_adid = value; }
    }
    private string _android_serial = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"android_serial", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_serial
    {
      get { return _android_serial; }
      set { _android_serial = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_LoginOnline")]
  public partial class Msg_S2C_LoginOnline : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_LoginOnline() {}
    
    private int _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private int _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private uint _reg_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"reg_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reg_time
    {
      get { return _reg_time; }
      set { _reg_time = value; }
    }
    private uint _golds;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private uint _diamonds;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"diamonds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamonds
    {
      get { return _diamonds; }
      set { _diamonds = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private uint _exp_value;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"exp_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_value
    {
      get { return _exp_value; }
      set { _exp_value = value; }
    }
    private uint _exp_level;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"exp_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_level
    {
      get { return _exp_level; }
      set { _exp_level = value; }
    }
    private uint _full_extent = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"full_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint full_extent
    {
      get { return _full_extent; }
      set { _full_extent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_PendingRegister")]
  public partial class Msg_C2S_PendingRegister : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_PendingRegister() {}
    
    private string _account_email;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_email
    {
      get { return _account_email; }
      set { _account_email = value; }
    }
    private string _account_pwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account_pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_pwd
    {
      get { return _account_pwd; }
      set { _account_pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_PendingRegister")]
  public partial class Msg_S2C_PendingRegister : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_PendingRegister() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_ModifyMyPasswd")]
  public partial class Msg_C2S_ModifyMyPasswd : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_ModifyMyPasswd() {}
    
    private string _old_passwd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"old_passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string old_passwd
    {
      get { return _old_passwd; }
      set { _old_passwd = value; }
    }
    private string _new_passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"new_passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string new_passwd
    {
      get { return _new_passwd; }
      set { _new_passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_ModifyMyPasswd")]
  public partial class Msg_S2C_ModifyMyPasswd : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_ModifyMyPasswd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GetMyProfile")]
  public partial class Msg_C2S_GetMyProfile : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GetMyProfile() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GetMyProfile")]
  public partial class Msg_S2C_GetMyProfile : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GetMyProfile() {}
    
    private string _account_email;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_email
    {
      get { return _account_email; }
      set { _account_email = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _region_name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"region_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string region_name
    {
      get { return _region_name; }
      set { _region_name = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private uint _golds;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private uint _diamonds;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"diamonds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamonds
    {
      get { return _diamonds; }
      set { _diamonds = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private uint _exp_value;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"exp_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_value
    {
      get { return _exp_value; }
      set { _exp_value = value; }
    }
    private uint _exp_level;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"exp_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_level
    {
      get { return _exp_level; }
      set { _exp_level = value; }
    }
    private bool _is_guest;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"is_guest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_guest
    {
      get { return _is_guest; }
      set { _is_guest = value; }
    }
    private bool _is_custom_head;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"is_custom_head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_custom_head
    {
      get { return _is_custom_head; }
      set { _is_custom_head = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private uint _full_extent = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"full_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint full_extent
    {
      get { return _full_extent; }
      set { _full_extent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_ModifyMyProfile")]
  public partial class Msg_C2S_ModifyMyProfile : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_ModifyMyProfile() {}
    
    private string _nick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _region_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"region_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string region_name
    {
      get { return _region_name; }
      set { _region_name = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_ModifyMyProfile")]
  public partial class Msg_S2C_ModifyMyProfile : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_ModifyMyProfile() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GetBindCode")]
  public partial class Msg_C2S_GetBindCode : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GetBindCode() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GetBindCode")]
  public partial class Msg_S2C_GetBindCode : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GetBindCode() {}
    
    private string _bind_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bind_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bind_code
    {
      get { return _bind_code; }
      set { _bind_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_BindTV")]
  public partial class Msg_C2S_BindTV : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_BindTV() {}
    
    private string _bind_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bind_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bind_code
    {
      get { return _bind_code; }
      set { _bind_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_BindTV")]
  public partial class Msg_S2C_BindTV : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_BindTV() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GetTVProfile")]
  public partial class Msg_C2S_GetTVProfile : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GetTVProfile() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GetTVProfile")]
  public partial class Msg_S2C_GetTVProfile : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GetTVProfile() {}
    
    private uint _tv_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tv_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tv_uid
    {
      get { return _tv_uid; }
      set { _tv_uid = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private uint _golds;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private uint _diamonds;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"diamonds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamonds
    {
      get { return _diamonds; }
      set { _diamonds = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_ModifyTVProfile")]
  public partial class Msg_C2S_ModifyTVProfile : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_ModifyTVProfile() {}
    
    private string _nick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_ModifyTVProfile")]
  public partial class Msg_S2C_ModifyTVProfile : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_ModifyTVProfile() {}
    
    private uint _tv_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tv_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tv_uid
    {
      get { return _tv_uid; }
      set { _tv_uid = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_AddExpValue")]
  public partial class Msg_C2S_AddExpValue : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_AddExpValue() {}
    
    private int _exp_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp_type
    {
      get { return _exp_type; }
      set { _exp_type = value; }
    }
    private int _exp_value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"exp_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp_value
    {
      get { return _exp_value; }
      set { _exp_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_AddExpValue")]
  public partial class Msg_S2C_AddExpValue : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_AddExpValue() {}
    
    private uint _exp_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_level
    {
      get { return _exp_level; }
      set { _exp_level = value; }
    }
    private uint _exp_value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"exp_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_value
    {
      get { return _exp_value; }
      set { _exp_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_ChangeGolds")]
  public partial class Msg_C2S_ChangeGolds : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_ChangeGolds() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _golds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_ChangeGolds")]
  public partial class Msg_S2C_ChangeGolds : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_ChangeGolds() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _golds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private uint _full_extent = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"full_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint full_extent
    {
      get { return _full_extent; }
      set { _full_extent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GetFullExtent")]
  public partial class Msg_C2S_GetFullExtent : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GetFullExtent() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GetFullExtent")]
  public partial class Msg_S2C_GetFullExtent : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GetFullExtent() {}
    
    private uint _full_extent;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"full_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint full_extent
    {
      get { return _full_extent; }
      set { _full_extent = value; }
    }
    private uint _clean_extent;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"clean_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint clean_extent
    {
      get { return _clean_extent; }
      set { _clean_extent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_ChangeExpGolds")]
  public partial class Msg_C2S_ChangeExpGolds : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_ChangeExpGolds() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_ChangeExpGolds")]
  public partial class Msg_S2C_ChangeExpGolds : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_ChangeExpGolds() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _full_extent;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"full_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint full_extent
    {
      get { return _full_extent; }
      set { _full_extent = value; }
    }
    private uint _clean_extent;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"clean_extent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint clean_extent
    {
      get { return _clean_extent; }
      set { _clean_extent = value; }
    }
    private uint _golds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private uint _exp_level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"exp_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_level
    {
      get { return _exp_level; }
      set { _exp_level = value; }
    }
    private uint _exp_value;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"exp_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_value
    {
      get { return _exp_value; }
      set { _exp_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GetUserGameLevel")]
  public partial class Msg_C2S_GetUserGameLevel : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GetUserGameLevel() {}
    
    private uint _game_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _game_level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_level
    {
      get { return _game_level; }
      set { _game_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserGameLevelRecord")]
  public partial class UserGameLevelRecord : global::ProtoBuf.IExtensible
  {
    public UserGameLevelRecord() {}
    
    private uint _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _game_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"game_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_level
    {
      get { return _game_level; }
      set { _game_level = value; }
    }
    private uint _duration;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private uint _star_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"star_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star_num
    {
      get { return _star_num; }
      set { _star_num = value; }
    }
    private uint _finsh_time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"finsh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint finsh_time
    {
      get { return _finsh_time; }
      set { _finsh_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GetUserGameLevel")]
  public partial class Msg_S2C_GetUserGameLevel : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GetUserGameLevel() {}
    
    private readonly global::System.Collections.Generic.List<SuperOnlineProto.UserGameLevelRecord> _records = new global::System.Collections.Generic.List<SuperOnlineProto.UserGameLevelRecord>();
    [global::ProtoBuf.ProtoMember(1, Name=@"records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SuperOnlineProto.UserGameLevelRecord> records
    {
      get { return _records; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_StartPlayGame")]
  public partial class Msg_C2S_StartPlayGame : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_StartPlayGame() {}
    
    private uint _game_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _game_level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_level
    {
      get { return _game_level; }
      set { _game_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_StartPlayGame")]
  public partial class Msg_S2C_StartPlayGame : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_StartPlayGame() {}
    
    private uint _record_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"record_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint record_id
    {
      get { return _record_id; }
      set { _record_id = value; }
    }
    private uint _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _game_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"game_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_level
    {
      get { return _game_level; }
      set { _game_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_EndPlayGame")]
  public partial class Msg_C2S_EndPlayGame : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_EndPlayGame() {}
    
    private uint _record_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"record_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint record_id
    {
      get { return _record_id; }
      set { _record_id = value; }
    }
    private uint _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _game_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"game_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_level
    {
      get { return _game_level; }
      set { _game_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_EndPlayGame")]
  public partial class Msg_S2C_EndPlayGame : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_EndPlayGame() {}
    
    private uint _record_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"record_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint record_id
    {
      get { return _record_id; }
      set { _record_id = value; }
    }
    private uint _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _game_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"game_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint game_level
    {
      get { return _game_level; }
      set { _game_level = value; }
    }
    private uint _duration;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private uint _star_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"star_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star_num
    {
      get { return _star_num; }
      set { _star_num = value; }
    }
    private uint _golds;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }
    private uint _exp_level;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exp_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_level
    {
      get { return _exp_level; }
      set { _exp_level = value; }
    }
    private uint _exp_value;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"exp_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp_value
    {
      get { return _exp_value; }
      set { _exp_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}