//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message/super.login.proto
namespace SuperLoginProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_Register")]
  public partial class Msg_C2S_Register : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_Register() {}
    
    private int _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private int _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private int _user_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_type
    {
      get { return _user_type; }
      set { _user_type = value; }
    }
    private string _account_email;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"account_email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_email
    {
      get { return _account_email; }
      set { _account_email = value; }
    }
    private string _account_pwd;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"account_pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_pwd
    {
      get { return _account_pwd; }
      set { _account_pwd = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _birthday;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _android_mac = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"android_mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_mac
    {
      get { return _android_mac; }
      set { _android_mac = value; }
    }
    private string _android_adid = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"android_adid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_adid
    {
      get { return _android_adid; }
      set { _android_adid = value; }
    }
    private string _android_serial = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"android_serial", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_serial
    {
      get { return _android_serial; }
      set { _android_serial = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_Register")]
  public partial class Msg_S2C_Register : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_Register() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GuestLogin")]
  public partial class Msg_C2S_GuestLogin : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GuestLogin() {}
    
    private int _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private int _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private int _user_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_type
    {
      get { return _user_type; }
      set { _user_type = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _android_mac = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"android_mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_mac
    {
      get { return _android_mac; }
      set { _android_mac = value; }
    }
    private string _android_adid = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"android_adid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_adid
    {
      get { return _android_adid; }
      set { _android_adid = value; }
    }
    private string _android_serial = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"android_serial", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string android_serial
    {
      get { return _android_serial; }
      set { _android_serial = value; }
    }
    private string _nick = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GuestLogin")]
  public partial class Msg_S2C_GuestLogin : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GuestLogin() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private bool _is_guest;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_guest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_guest
    {
      get { return _is_guest; }
      set { _is_guest = value; }
    }
    private byte[] _session;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_Login")]
  public partial class Msg_C2S_Login : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_Login() {}
    
    private int _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private int _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _account_email;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"account_email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_email
    {
      get { return _account_email; }
      set { _account_email = value; }
    }
    private string _account_pwd;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"account_pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_pwd
    {
      get { return _account_pwd; }
      set { _account_pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_Login")]
  public partial class Msg_S2C_Login : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_Login() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private bool _is_guest;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_guest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_guest
    {
      get { return _is_guest; }
      set { _is_guest = value; }
    }
    private byte[] _session;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_ResetMyPasswd")]
  public partial class Msg_C2S_ResetMyPasswd : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_ResetMyPasswd() {}
    
    private string _account_email;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_email
    {
      get { return _account_email; }
      set { _account_email = value; }
    }
    private string _new_passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"new_passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string new_passwd
    {
      get { return _new_passwd; }
      set { _new_passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_ResetMyPasswd")]
  public partial class Msg_S2C_ResetMyPasswd : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_ResetMyPasswd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S_GetOnlineIpPort")]
  public partial class Msg_C2S_GetOnlineIpPort : global::ProtoBuf.IExtensible
  {
    public Msg_C2S_GetOnlineIpPort() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C_GetOnlineIpPort")]
  public partial class Msg_S2C_GetOnlineIpPort : global::ProtoBuf.IExtensible
  {
    public Msg_S2C_GetOnlineIpPort() {}
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}