//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bag.proto
// Note: requires additional types generated from: login.proto
namespace proto.bag
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageRequest")]
  public partial class PackageRequest : global::ProtoBuf.IExtensible
  {
    public PackageRequest() {}
    
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageInfoResponse")]
  public partial class PackageInfoResponse : global::ProtoBuf.IExtensible
  {
    public PackageInfoResponse() {}
    
    private int _used = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int used
    {
      get { return _used; }
      set { _used = value; }
    }
    private int _total = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total
    {
      get { return _total; }
      set { _total = value; }
    }
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageItemListResponse")]
  public partial class PackageItemListResponse : global::ProtoBuf.IExtensible
  {
    public PackageItemListResponse() {}
    
    private int _sign;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sign", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sign
    {
      get { return _sign; }
      set { _sign = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.bag.ItemResponse> _itemList = new global::System.Collections.Generic.List<proto.bag.ItemResponse>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.bag.ItemResponse> itemList
    {
      get { return _itemList; }
    }
  
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddNewItemNumResponse")]
  public partial class AddNewItemNumResponse : global::ProtoBuf.IExtensible
  {
    public AddNewItemNumResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.bag.ItemResponse> _itemList = new global::System.Collections.Generic.List<proto.bag.ItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.bag.ItemResponse> itemList
    {
      get { return _itemList; }
    }
  
    private bool _isPick = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isPick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPick
    {
      get { return _isPick; }
      set { _isPick = value; }
    }
    private bool _playEffect = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool playEffect
    {
      get { return _playEffect; }
      set { _playEffect = value; }
    }
    private int _sellId = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sellId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int sellId
    {
      get { return _sellId; }
      set { _sellId = value; }
    }
    private bool _isBackBuy = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isBackBuy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool isBackBuy
    {
      get { return _isBackBuy; }
      set { _isBackBuy = value; }
    }
    private bool _isSell = (bool)false;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isSell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool isSell
    {
      get { return _isSell; }
      set { _isSell = value; }
    }
    private proto.bag.AddItemWay _type = proto.bag.AddItemWay.DRAGTOBAG;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.AddItemWay.DRAGTOBAG)]
    public proto.bag.AddItemWay type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemResponse")]
  public partial class ItemResponse : global::ProtoBuf.IExtensible
  {
    public ItemResponse() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _itemid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private int _amount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private proto.bag.ItemType _itemType = proto.bag.ItemType.MONEY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.ItemType.MONEY)]
    public proto.bag.ItemType itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private bool _isBound = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isBound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBound
    {
      get { return _isBound; }
      set { _isBound = value; }
    }
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RomoveItemRequestAndResponse")]
  public partial class RomoveItemRequestAndResponse : global::ProtoBuf.IExtensible
  {
    public RomoveItemRequestAndResponse() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SplitItemRequest")]
  public partial class SplitItemRequest : global::ProtoBuf.IExtensible
  {
    public SplitItemRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _amount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SplitItemResponse")]
  public partial class SplitItemResponse : global::ProtoBuf.IExtensible
  {
    public SplitItemResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.bag.ItemResponse> _itemList = new global::System.Collections.Generic.List<proto.bag.ItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.bag.ItemResponse> itemList
    {
      get { return _itemList; }
    }
  
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DragItemRequest")]
  public partial class DragItemRequest : global::ProtoBuf.IExtensible
  {
    public DragItemRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DragItemResponse")]
  public partial class DragItemResponse : global::ProtoBuf.IExtensible
  {
    public DragItemResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.bag.ItemResponse> _itemList = new global::System.Collections.Generic.List<proto.bag.ItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.bag.ItemResponse> itemList
    {
      get { return _itemList; }
    }
  
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnlockBoxRequest")]
  public partial class UnlockBoxRequest : global::ProtoBuf.IExtensible
  {
    public UnlockBoxRequest() {}
    
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private proto.bag.PackageType _type = proto.bag.PackageType.BAG;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.bag.PackageType.BAG)]
    public proto.bag.PackageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveRequest")]
  public partial class MoveRequest : global::ProtoBuf.IExtensible
  {
    public MoveRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveResponse")]
  public partial class MoveResponse : global::ProtoBuf.IExtensible
  {
    public MoveResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.bag.ItemResponse> _itemList = new global::System.Collections.Generic.List<proto.bag.ItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.bag.ItemResponse> itemList
    {
      get { return _itemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseItemRequestAndResponse")]
  public partial class UseItemRequestAndResponse : global::ProtoBuf.IExtensible
  {
    public UseItemRequestAndResponse() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _amount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SeeItemRequest")]
  public partial class SeeItemRequest : global::ProtoBuf.IExtensible
  {
    public SeeItemRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _roleId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PackageType")]
    public enum PackageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAG", Value=1)]
      BAG = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AddItemWay")]
    public enum AddItemWay
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRAGTOBAG", Value=1)]
      DRAGTOBAG = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXCHANGE", Value=2)]
      EXCHANGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REWARD", Value=3)]
      REWARD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUYBACK", Value=4)]
      BUYBACK = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLDBUY", Value=5)]
      GOLDBUY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIAMOND", Value=6)]
      DIAMOND = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GIFTBAG", Value=8)]
      GIFTBAG = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ConsumeItemWay")]
    public enum ConsumeItemWay
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRAGTOWAREROOM", Value=1)]
      DRAGTOWAREROOM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROPPED", Value=2)]
      DROPPED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMELT", Value=3)]
      SMELT = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemType")]
    public enum ItemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONEY", Value=1)]
      MONEY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXPEND", Value=2)]
      EXPEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATERIAL", Value=3)]
      MATERIAL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEBRIS", Value=4)]
      DEBRIS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP", Value=5)]
      EQUIP = 5
    }
  
}