//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: cmd.proto
namespace proto.cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"PushCmd")]
    public enum PushCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeExp", Value=20)]
      ChangeExp = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeMoney", Value=21)]
      ChangeMoney = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroChange", Value=1199)]
      HeroChange = 1199,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChallengeResult", Value=1299)]
      ChallengeResult = 1299,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroAngerChange", Value=1298)]
      HeroAngerChange = 1298,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroBagChange", Value=1297)]
      HeroBagChange = 1297,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchingSuccess", Value=1399)]
      MatchingSuccess = 1399,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DropEnergyBean", Value=1396)]
      DropEnergyBean = 1396,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameStart", Value=1394)]
      GameStart = 1394,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameStop", Value=1393)]
      GameStop = 1393,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenFunction", Value=1499)]
      OpenFunction = 1499,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunctionInfo", Value=1498)]
      FunctionInfo = 1498,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeductItems", Value=1599)]
      DeductItems = 1599,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItems", Value=1598)]
      AddItems = 1598,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNewItems", Value=1597)]
      AddNewItems = 1597,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateItemVo", Value=1596)]
      UpdateItemVo = 1596,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewMail", Value=1699)]
      NewMail = 1699
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EchoCmd")]
    public enum EchoCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Sync", Value=0)]
      Sync = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat", Value=10)]
      Chat = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=1001)]
      Login = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateName", Value=1002)]
      CreateName = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroInfo", Value=1101)]
      HeroInfo = 1101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DefaultSetting", Value=1102)]
      DefaultSetting = 1102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeDefaultSet", Value=1103)]
      ChangeDefaultSet = 1103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChallengeDungeon", Value=1201)]
      ChallengeDungeon = 1201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChallengeDungeonInfo", Value=1202)]
      ChallengeDungeonInfo = 1202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChallengeExit", Value=1203)]
      ChallengeExit = 1203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PutInHero", Value=1204)]
      PutInHero = 1204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DungeonInfo", Value=1205)]
      DungeonInfo = 1205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OperationInfo", Value=1206)]
      OperationInfo = 1206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickEnergyBean", Value=1207)]
      PickEnergyBean = 1207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchingPvp", Value=1301)]
      MatchingPvp = 1301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelMatchingPvp", Value=1302)]
      CancelMatchingPvp = 1302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LISTPACKAGEITEM", Value=1310)]
      LISTPACKAGEITEM = 1310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LISTMAIL", Value=1401)]
      LISTMAIL = 1401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAILDETAIL", Value=1402)]
      MAILDETAIL = 1402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SENDMAIL", Value=1403)]
      SENDMAIL = 1403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECEIVEATTACHMENT", Value=1404)]
      RECEIVEATTACHMENT = 1404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETEMAIL", Value=1405)]
      DELETEMAIL = 1405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMREQUEST", Value=9900)]
      GMREQUEST = 9900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendLog", Value=9901)]
      SendLog = 9901
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCmd")]
    public enum ErrorCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=9999)]
      ERROR = 9999
    }
  
}