//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: errorcode.proto
namespace proto.errorcode
{
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCodeResponse")]
    public enum ErrorCodeResponse
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LllegalCharacter", Value=9000)]
      LllegalCharacter = 9000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorOfRoleFormmat", Value=9001)]
      ErrorOfRoleFormmat = 9001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RolenameExist", Value=9002)]
      RolenameExist = 9002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorOfPassword", Value=9003)]
      ErrorOfPassword = 9003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShortName", Value=9004)]
      ShortName = 9004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BagPositionNotEnough", Value=9010)]
      BagPositionNotEnough = 9010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotHero", Value=9100)]
      NotHero = 9100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotRepeatSetHero", Value=9101)]
      NotRepeatSetHero = 9101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotRepeatSetPosition", Value=9102)]
      NotRepeatSetPosition = 9102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpHeroMoreMax", Value=9110)]
      UpHeroMoreMax = 9110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpareHeroMoreMax", Value=9111)]
      SpareHeroMoreMax = 9111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemNotEnough", Value=9120)]
      ItemNotEnough = 9120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PutInHeroCD", Value=9130)]
      PutInHeroCD = 9130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnergyNotEnough", Value=9131)]
      EnergyNotEnough = 9131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroAlreadyDead", Value=9132)]
      HeroAlreadyDead = 9132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WoodNotPutInHero", Value=9133)]
      WoodNotPutInHero = 9133
    }
  
}