//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game.proto
namespace proto.game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StateSyncRequest")]
  public partial class StateSyncRequest : global::ProtoBuf.IExtensible
  {
    public StateSyncRequest() {}
    
    private proto.game.SyncType _syncType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"syncType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.game.SyncType syncType
    {
      get { return _syncType; }
      set { _syncType = value; }
    }
    private proto.game.AttackRequest _attackRequest = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.game.AttackRequest attackRequest
    {
      get { return _attackRequest; }
      set { _attackRequest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StateSync")]
  public partial class StateSync : global::ProtoBuf.IExtensible
  {
    public StateSync() {}
    
    private proto.game.SyncType _syncType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"syncType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.game.SyncType syncType
    {
      get { return _syncType; }
      set { _syncType = value; }
    }
    private proto.game.AttackResponse _attackResponse = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attackResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.game.AttackResponse attackResponse
    {
      get { return _attackResponse; }
      set { _attackResponse = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.game.BuffResponse> _buffResponse = new global::System.Collections.Generic.List<proto.game.BuffResponse>();
    [global::ProtoBuf.ProtoMember(3, Name=@"buffResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.BuffResponse> buffResponse
    {
      get { return _buffResponse; }
    }
  
    private proto.game.PutInHeroChange _heroChange = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"heroChange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.game.PutInHeroChange heroChange
    {
      get { return _heroChange; }
      set { _heroChange = value; }
    }
    private proto.game.RemoveHeroCardResponse _removeCard = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"removeCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.game.RemoveHeroCardResponse removeCard
    {
      get { return _removeCard; }
      set { _removeCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveHeroCardResponse")]
  public partial class RemoveHeroCardResponse : global::ProtoBuf.IExtensible
  {
    public RemoveHeroCardResponse() {}
    
    private int _ownerIndex = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ownerIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ownerIndex
    {
      get { return _ownerIndex; }
      set { _ownerIndex = value; }
    }
    private int _heroId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttackRequest")]
  public partial class AttackRequest : global::ProtoBuf.IExtensible
  {
    public AttackRequest() {}
    
    private int _skillId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _latticeNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"latticeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int latticeNum
    {
      get { return _latticeNum; }
      set { _latticeNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttackResponse")]
  public partial class AttackResponse : global::ProtoBuf.IExtensible
  {
    public AttackResponse() {}
    
    private int _attacker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.game.Target> _targets = new global::System.Collections.Generic.List<proto.game.Target>();
    [global::ProtoBuf.ProtoMember(3, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.Target> targets
    {
      get { return _targets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuffResponse")]
  public partial class BuffResponse : global::ProtoBuf.IExtensible
  {
    public BuffResponse() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _buffId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buffId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buffId
    {
      get { return _buffId; }
      set { _buffId = value; }
    }
    private int _remianTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"remianTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remianTime
    {
      get { return _remianTime; }
      set { _remianTime = value; }
    }
    private bool _isAdd = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isAdd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAdd
    {
      get { return _isAdd; }
      set { _isAdd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonInfoResponse")]
  public partial class DungeonInfoResponse : global::ProtoBuf.IExtensible
  {
    public DungeonInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.game.BattleHeroInfo> _battleHeros = new global::System.Collections.Generic.List<proto.game.BattleHeroInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"battleHeros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.BattleHeroInfo> battleHeros
    {
      get { return _battleHeros; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.game.GameHeroInfo> _heros = new global::System.Collections.Generic.List<proto.game.GameHeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.GameHeroInfo> heros
    {
      get { return _heros; }
    }
  
    private int _teamNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"teamNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamNum
    {
      get { return _teamNum; }
      set { _teamNum = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.game.UserInfo> _userInfos = new global::System.Collections.Generic.List<proto.game.UserInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"userInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.UserInfo> userInfos
    {
      get { return _userInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.game.SkillInfo> _skillInfo = new global::System.Collections.Generic.List<proto.game.SkillInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"skillInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.SkillInfo> skillInfo
    {
      get { return _skillInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.game.EnergyBean> _energyBeans = new global::System.Collections.Generic.List<proto.game.EnergyBean>();
    [global::ProtoBuf.ProtoMember(6, Name=@"energyBeans", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.EnergyBean> energyBeans
    {
      get { return _energyBeans; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnergyBean")]
  public partial class EnergyBean : global::ProtoBuf.IExtensible
  {
    public EnergyBean() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillInfo")]
  public partial class SkillInfo : global::ProtoBuf.IExtensible
  {
    public SkillInfo() {}
    
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _roleType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleType
    {
      get { return _roleType; }
      set { _roleType = value; }
    }
    private string _roleName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private int _teamNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"teamNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamNum
    {
      get { return _teamNum; }
      set { _teamNum = value; }
    }
    private int _energy = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _heroId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> heroId
    {
      get { return _heroId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Target")]
  public partial class Target : global::ProtoBuf.IExtensible
  {
    public Target() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _loss = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loss
    {
      get { return _loss; }
      set { _loss = value; }
    }
    private proto.game.AttackType _attackType = proto.game.AttackType.Hit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.game.AttackType.Hit)]
    public proto.game.AttackType attackType
    {
      get { return _attackType; }
      set { _attackType = value; }
    }
    private int _current = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"current", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current
    {
      get { return _current; }
      set { _current = value; }
    }
    private int _maxHp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _anger = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"anger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int anger
    {
      get { return _anger; }
      set { _anger = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroAngerChangeResponse")]
  public partial class HeroAngerChangeResponse : global::ProtoBuf.IExtensible
  {
    public HeroAngerChangeResponse() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _anger = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"anger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int anger
    {
      get { return _anger; }
      set { _anger = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HpChangeResponse")]
  public partial class HpChangeResponse : global::ProtoBuf.IExtensible
  {
    public HpChangeResponse() {}
    
    private proto.game.Target _targets = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.game.Target targets
    {
      get { return _targets; }
      set { _targets = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PutInHeroChange")]
  public partial class PutInHeroChange : global::ProtoBuf.IExtensible
  {
    public PutInHeroChange() {}
    
    private proto.game.BattleHeroInfo _battleHero = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battleHero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.game.BattleHeroInfo battleHero
    {
      get { return _battleHero; }
      set { _battleHero = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleHeroInfo")]
  public partial class BattleHeroInfo : global::ProtoBuf.IExtensible
  {
    public BattleHeroInfo() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _heroId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _maxHp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _teamNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"teamNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamNum
    {
      get { return _teamNum; }
      set { _teamNum = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.game.BuffResponse> _buffResponse = new global::System.Collections.Generic.List<proto.game.BuffResponse>();
    [global::ProtoBuf.ProtoMember(7, Name=@"buffResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.game.BuffResponse> buffResponse
    {
      get { return _buffResponse; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChanllengeResult")]
  public partial class ChanllengeResult : global::ProtoBuf.IExtensible
  {
    public ChanllengeResult() {}
    
    private int _winTeamId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"winTeamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winTeamId
    {
      get { return _winTeamId; }
      set { _winTeamId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameHeroInfo")]
  public partial class GameHeroInfo : global::ProtoBuf.IExtensible
  {
    public GameHeroInfo() {}
    
    private int _heroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchingSuccessResponse")]
  public partial class MatchingSuccessResponse : global::ProtoBuf.IExtensible
  {
    public MatchingSuccessResponse() {}
    
    private int _pvpMapId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pvpMapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pvpMapId
    {
      get { return _pvpMapId; }
      set { _pvpMapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroBagChange")]
  public partial class HeroBagChange : global::ProtoBuf.IExtensible
  {
    public HeroBagChange() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _heroId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OperationInfo")]
  public partial class OperationInfo : global::ProtoBuf.IExtensible
  {
    public OperationInfo() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PickEnergyBean")]
  public partial class PickEnergyBean : global::ProtoBuf.IExtensible
  {
    public PickEnergyBean() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendLog")]
  public partial class SendLog : global::ProtoBuf.IExtensible
  {
    public SendLog() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SyncType")]
    public enum SyncType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Attack", Value=1)]
      Attack = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AttackResult", Value=2)]
      AttackResult = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HpChange", Value=3)]
      HpChange = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuffChange", Value=4)]
      BuffChange = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroChange", Value=5)]
      HeroChange = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveHeroCard", Value=6)]
      RemoveHeroCard = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeartBeat", Value=7)]
      HeartBeat = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AttackType")]
    public enum AttackType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hit", Value=1)]
      Hit = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Miss", Value=2)]
      Miss = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cri", Value=3)]
      Cri = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Secondkill", Value=4)]
      Secondkill = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Immune", Value=5)]
      Immune = 5
    }
  
}