//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hero.proto
namespace proto.hero
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfoResponse")]
  public partial class HeroInfoResponse : global::ProtoBuf.IExtensible
  {
    public HeroInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.hero.HeroInfo> _heros = new global::System.Collections.Generic.List<proto.hero.HeroInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.hero.HeroInfo> heros
    {
      get { return _heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private int _heroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DefaultSettingResponse")]
  public partial class DefaultSettingResponse : global::ProtoBuf.IExtensible
  {
    public DefaultSettingResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.hero.HeroInfo> _heros = new global::System.Collections.Generic.List<proto.hero.HeroInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.hero.HeroInfo> heros
    {
      get { return _heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeDefaultSetRequest")]
  public partial class ChangeDefaultSetRequest : global::ProtoBuf.IExtensible
  {
    public ChangeDefaultSetRequest() {}
    
    private int _heroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _stageId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Attributes")]
    public enum Attributes
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MaxHp", Value=1)]
      MaxHp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PhysicsHurt", Value=2)]
      PhysicsHurt = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MagicHurt", Value=3)]
      MagicHurt = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarLawHurt", Value=4)]
      WarLawHurt = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddHp", Value=5)]
      AddHp = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPhysicsHurt", Value=6)]
      AddPhysicsHurt = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddMagicHurt", Value=7)]
      AddMagicHurt = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddWarLawHurt", Value=8)]
      AddWarLawHurt = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Power", Value=11)]
      Power = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Intelligence", Value=12)]
      Intelligence = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Commander", Value=13)]
      Commander = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPower", Value=14)]
      AddPower = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddIntelligence", Value=15)]
      AddIntelligence = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddCommander", Value=16)]
      AddCommander = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Miss", Value=21)]
      Miss = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cri", Value=22)]
      Cri = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Secondkill", Value=23)]
      Secondkill = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Att31", Value=31)]
      Att31 = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Att32", Value=32)]
      Att32 = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Att33", Value=33)]
      Att33 = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Att34", Value=34)]
      Att34 = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Att35", Value=35)]
      Att35 = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Att36", Value=36)]
      Att36 = 36
    }
  
}