//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace proto.login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfoRequest")]
  public partial class UserInfoRequest : global::ProtoBuf.IExtensible
  {
    public UserInfoRequest() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _platform;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private string _platform;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _passward = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"passward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string passward
    {
      get { return _passward; }
      set { _passward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateNameRequest")]
  public partial class CreateNameRequest : global::ProtoBuf.IExtensible
  {
    public CreateNameRequest() {}
    
    private int _roleType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleType
    {
      get { return _roleType; }
      set { _roleType = value; }
    }
    private string _roleName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private proto.login.UserInfo _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.login.UserInfo data
    {
      get { return _data; }
      set { _data = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private long _yuanbao = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long yuanbao
    {
      get { return _yuanbao; }
      set { _yuanbao = value; }
    }
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _serverId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private int _roleType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleType
    {
      get { return _roleType; }
      set { _roleType = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserMoneyChangedResponse")]
  public partial class UserMoneyChangedResponse : global::ProtoBuf.IExtensible
  {
    public UserMoneyChangedResponse() {}
    
    private proto.login.CurrencyType _currencyType = proto.login.CurrencyType.Gold;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"currencyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.login.CurrencyType.Gold)]
    public proto.login.CurrencyType currencyType
    {
      get { return _currencyType; }
      set { _currencyType = value; }
    }
    private long _amount = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalentResponse")]
  public partial class TalentResponse : global::ProtoBuf.IExtensible
  {
    public TalentResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.login.TalentInfo> _talent = new global::System.Collections.Generic.List<proto.login.TalentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"talent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.login.TalentInfo> talent
    {
      get { return _talent; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalentInfo")]
  public partial class TalentInfo : global::ProtoBuf.IExtensible
  {
    public TalentInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CurrencyType")]
    public enum CurrencyType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gold", Value=1)]
      Gold = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Yuanbao", Value=2)]
      Yuanbao = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Energy", Value=3)]
      Energy = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Exp", Value=4)]
      Exp = 4
    }
  
}