//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mail.proto
// Note: requires additional types generated from: bag.proto
namespace proto.mail
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListRequest")]
  public partial class ListRequest : global::ProtoBuf.IExtensible
  {
    public ListRequest() {}
    
    private int _page = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private bool _isAttachment = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isAttachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAttachment
    {
      get { return _isAttachment; }
      set { _isAttachment = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListResponse")]
  public partial class ListResponse : global::ProtoBuf.IExtensible
  {
    public ListResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.mail.MailResponse> _mailResponse = new global::System.Collections.Generic.List<proto.mail.MailResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mailResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.mail.MailResponse> mailResponse
    {
      get { return _mailResponse; }
    }
  
    private int _mailAmount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mailAmount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mailAmount
    {
      get { return _mailAmount; }
      set { _mailAmount = value; }
    }
    private int _unread = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unread", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int unread
    {
      get { return _unread; }
      set { _unread = value; }
    }
    private int _total = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total
    {
      get { return _total; }
      set { _total = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailResponse")]
  public partial class MailResponse : global::ProtoBuf.IExtensible
  {
    public MailResponse() {}
    
    private int _mailType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mailType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mailType
    {
      get { return _mailType; }
      set { _mailType = value; }
    }
    private int _mid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mid
    {
      get { return _mid; }
      set { _mid = value; }
    }
    private bool _isRead = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isRead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isRead
    {
      get { return _isRead; }
      set { _isRead = value; }
    }
    private bool _isReceive = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isReceive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isReceive
    {
      get { return _isReceive; }
      set { _isReceive = value; }
    }
    private string _createDate = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"createDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string createDate
    {
      get { return _createDate; }
      set { _createDate = value; }
    }
    private string _deleteDate = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"deleteDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deleteDate
    {
      get { return _deleteDate; }
      set { _deleteDate = value; }
    }
    private bool _isAttachment = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isAttachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAttachment
    {
      get { return _isAttachment; }
      set { _isAttachment = value; }
    }
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private proto.mail.SendType _sendType = proto.mail.SendType.Offline;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"sendType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.mail.SendType.Offline)]
    public proto.mail.SendType sendType
    {
      get { return _sendType; }
      set { _sendType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailRequest")]
  public partial class MailRequest : global::ProtoBuf.IExtensible
  {
    public MailRequest() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDetailResponse")]
  public partial class MailDetailResponse : global::ProtoBuf.IExtensible
  {
    public MailDetailResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.bag.ItemResponse> _itemList = new global::System.Collections.Generic.List<proto.bag.ItemResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.bag.ItemResponse> itemList
    {
      get { return _itemList; }
    }
  
    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private int _mailType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mailType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mailType
    {
      get { return _mailType; }
      set { _mailType = value; }
    }
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private proto.mail.SendType _sendType = proto.mail.SendType.Offline;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sendType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.mail.SendType.Offline)]
    public proto.mail.SendType sendType
    {
      get { return _sendType; }
      set { _sendType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteRequest")]
  public partial class DeleteRequest : global::ProtoBuf.IExtensible
  {
    public DeleteRequest() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SendType")]
    public enum SendType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Offline", Value=1)]
      Offline = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BagFull", Value=0)]
      BagFull = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotReceive", Value=2)]
      NotReceive = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"titleNotice", Value=7)]
      titleNotice = 7
    }
  
}