//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: openfunction.proto
namespace proto.openfunction
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenFuncitonResponse")]
  public partial class OpenFuncitonResponse : global::ProtoBuf.IExtensible
  {
    public OpenFuncitonResponse() {}
    
    private readonly global::System.Collections.Generic.List<proto.openfunction.FunctionVo> _functionVo = new global::System.Collections.Generic.List<proto.openfunction.FunctionVo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"functionVo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.openfunction.FunctionVo> functionVo
    {
      get { return _functionVo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunctionVo")]
  public partial class FunctionVo : global::ProtoBuf.IExtensible
  {
    public FunctionVo() {}
    
    private int _functionId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"functionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int functionId
    {
      get { return _functionId; }
      set { _functionId = value; }
    }
    private bool _isOpen = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOpen
    {
      get { return _isOpen; }
      set { _isOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}